operators-manual/button-functions.md

buttons-functions: Add buttons default state

---

SUMMARY.md
developers/pymavlink.md
introduction/features.md
operators-manual/failsafes.md
operators-manual/full-parameter-list.md
operators-manual/logging.md
operators-manual/rc-input-and-output.md
troubleshooting/troubleshooting.md

[WIP] Developers: Add pymavlink

---

developers/pymavlink.md

[Link.](https://discuss.bluerobotics.com/t/autonomous-bluerov2-mavlink-ardusub-help/1761/48?u=patrickelectric)

pymavlink: Update comment of manual control example

---

developers/pymavlink.md

pymavlink: Add request, read and write parameters

---

developers/developers.md

The identantion level makes the text appears inside a code box

developers: Remove indentation level of text

---

developers/pymavlink.md

- Explain all connection types
- Add more explicit surface computer and companion connection examples
- Update all examples to be more clear with new information and companion

Improves and corrects pymavlink documentation

---

developers/sitl.md

developers: Add sitl troubleshooting

---

developers/developers.md

developers: Add ardusub troubleshooting

---

troubleshooting/troubleshooting.md

Add screen resolution tip to ardusub.com Troubleshooting tab

---

troubleshooting/troubleshooting.md

troubleshooting: Add terminal web app

---

developers/building-docs.md
developers/developers.md
footer.html
getting-started/initial-setup.md
hardware/components.md
introduction/applications.md
operators-manual/button-functions.md
operators-manual/failsafes.md
operators-manual/flight-modes.md
operators-manual/logging.md
operators-manual/parameters.md
resources/downloads.md
software/ardusub-firmware.md
software/components.md
troubleshooting/troubleshooting.md

Move issues link from ardusub-docs to ardusub-gitbook

---

troubleshooting/troubleshooting.md

troubleshooting: Add more test instructions

---

software/mavlink.md

mavlink: Add official website

---

operators-manual/arming-checks.md
operators-manual/button-functions.md

The outline currently is not being generated because we are missing hierarchy levels (going from h1 to h3 or h1 to h4)
fix #4

Change headers hierarchy

---

developers/pymavlink.md

pymavlink: Make test more explicit and clear

---

operators-manual/button-functions.md

Fix https://github.com/bluerobotics/ardusub-gitbook/issues/68

button-functions: add doc about roll-pitch-toggle

---

getting-started/initial-setup.md
troubleshooting/troubleshooting.md

fix https://github.com/bluerobotics/bluerobotics.github.io/issues/26

Mention "Enable joystick input" checkbox in initial setup and troubleshooting

---

.travis.yml

This will build master and push changes to gh-pages.

Use travis to deploy to gh-pages

---

CNAME

This file actually needs to be on `gh-pages` branch. Adding it here makes gitbook add it to the `_book` directory so it gets pushed to `gh-pages` alongside the other files.

Add CNAME to master branch

---

README.md
hardware/components.md
introduction/applications.md
introduction/features.md
operators-manual/flight-modes.md
operators-manual/logging.md
software/components.md

This adds some links back to bluerobotics.com, fixes old/broken links, and updates old information along the way.

SEO review

---

operators-manual/companion-web.md

Is this how it was supposed to work? It is the only way I got it to work here.
you can receive the serial device with `nc -ulp <port>` and write to it with `nc -u 192.168.2.2 <port>` 
I couldn't get socat to work properly either.

Add example of routing

---

developers/pymavlink.md

pymavlink: Fix mavlink website domain

---

developers/gps-positioning.md

This relative link needed to be fixed

Fix EK2 Parameters Link

---

operators-manual/companion-web.md

companion-web: Add MAVLink REST API

---

developers/developers.md
operators-manual/companion-web.md

Currently they look like this:
And should look like this:

Fix usage of **notes**

---

getting-started/installation-MDONLY.md
operators-manual/software-update.md
resources/downloads.md

follow up https://github.com/bluerobotics/ardusub-gitbook/pull/105

Change more QGC links to point upstream

---

resources/downloads.md

Fix ardusub version, some links and board name

Update downloads page

---

developers/pymavlink.md

@patrickelectric and I have been using it with Python 3 for a while now. And Python2 is EOL

Updates to pymavlink

---

troubleshooting/troubleshooting.md

troubleshooting: add section to reset mavproxy defaults

---

.travis.yml
book.json
developers/pymavlink.md
developers/pymavlink/arm_disarm.py
developers/pymavlink/camera_gimbal.py
developers/pymavlink/change_flight_mode.py
developers/pymavlink/companion_computer.py
developers/pymavlink/filter_messages.py
developers/pymavlink/manual_control.py
developers/pymavlink/rc_joystick.py
developers/pymavlink/read_params.py
developers/pymavlink/read_write_params.py
developers/pymavlink/send_gps.py
developers/pymavlink/send_rangefinder_vision.py
developers/pymavlink/serial_connection.py
developers/pymavlink/udp_connection.py

TODO:
This includes a few Python3 fixes as well

Make pymavlink scripts external, run pylint on all of them, and add pylint to CI

---

SUMMARY.md
developers/full-parameter-list.md
developers/wireless-topside.md

Update Developers section

---

SUMMARY.md

Begin cleanup of old documentation

Remove Operator's Manual Section from Summary.md (Do this last!)

---

developers/rc-input-and-output.md
introduction/required-software/companion-computer-software.md

rc-input-and-output: Add BRD_PWM_COUNT table

---

introduction/hardware-options/required-hardware/power-sensing-module.md

power-sensing-module: Fix mRobotics classic BEC link

---

developers/pymavlink.md
developers/pymavlink/request_message_interval.py

pymavlink: Add request_message_interval example

---

.github/workflows/pagesdeploy.yaml
developers/pymavlink/request_message_interval.py

Deploy github action was not running the same tests with PRs, this PR will change that to run all tests in PRs and use the deploy only for master branch.
This also fixes the problem that's making the tests fail.

Fix master

---

developers/dvl-integration.md
getting-started/installation-MDONLY.md
getting-started/installation.md
introduction/hardware-options/required-hardware/joystick.md
quick-start/installing-qgc.md

Plus a couple of broken link fixes

Change QGC links to our S3

---

.github/workflows/htmlproofer.yaml

I'm tired of finding broken links when opening prs..

CI: run weekly to check for broken links

---

developers/pymavlink/rc_joystick.py
developers/rc-input-and-output.md

rc-input: describe camera tilt param

---

developers/pymavlink/send_gps.py
developers/pymavlink/set_target_depth_attitude.py

Replace with meaningful flag/enum names.

Pymavlink remove magic bitmasks

---

.github/workflows/pagesdeploy.yaml

Our code was also created to work with python2

CI: Disable fstring check in pylint

---

quick-start/installing-companion.md

Don't merge until new build is available at
https://s3.amazonaws.com/downloads.bluerobotics.com/Pi/stable/ardusub-raspbian.img.zip
Once merged I need to update the BR website.
Have added an 'updated' date this time, which was requested by someone on the forum a little while ago. Happy to discuss/change the format or location or something as required. Specified YYYY-Mon-DD to avoid any potential confusion over date formats, although I'd also be happy with DD-Mon-YYYY, or swapping the dashes (-) for slashes (/). Thinking it should maybe be smaller than the main text to avoid drawing too much attention, which can be accomplished with `<sup>` <sup>sup</sup> or `<sub>` <sub>sub</sub>, or `<sub><sup>` <sub><sup>sub sup</sup></sub> if we want it centered (albeit at the cost of some extra size …

installing-companion: 0.0.28 -> 0.0.29

---

introduction/hardware-options/additional-peripheral-devices/underwater-positioning.md
introduction/hardware-options/required-hardware/power-supply.md
quick-start/installing-companion.md

Merge once built image has been updated.
Also need to update website, and I'm planning to make a forum post announcing the 'dvl available by default' change (and that this is hopefully the last update before companion beta becomes the real one).

quick-start: installing-companion: 0.0.29 -> 0.0.31

---

developers/dvl-integration.md
developers/pymavlink.md
introduction/hardware-options/required-hardware/autopilot.md
resources/downloads.md

- fixes #235 
- fixes #237 
- fixes #205

Fix minor issues

---

developers/opencv.md

- updated desktop install instructions to Ubuntu 20.04 w/ Python 3
- avoids unnecessarily displaying the same frame multiple times in Python example

opencv: update install instructions, improve python example

---

quick-start/installing-qgc.md

Update recommended version from 4.0.5 -> 4.1.6

quick-start: installing-qgc: recommend new version

---

developers/pymavlink/change_flight_mode.py

Closes https://github.com/bluerobotics/ardusub-gitbook/issues/245

change_flight_mode.py: Use the updated constant

---

introduction/hardware-options/additional-peripheral-devices/underwater-positioning.md

Fix Waterlinked GPS URL
