developers/pymavlink.md
=> pymavlink: Correct manual_control information

operators-manual/companion-web.md
This adds a link in the Companion page to the install page where it can be downloaded.
I was looking for the download link and google got me to companion-web.md instead, so I figured it should be easier to get to the download link from there.
=> Add install link

getting-started/initial-setup.md
Docs update after https://github.com/bluerobotics/flash/pull/27
Should we mention a date where it started or something?
=> Add information about default calibration parameters

getting-started/installation.md
Fix #89 
This will mean we'll have basically no control of what version is in use.
=> installation: update QGC links to point upstream

operators-manual/companion-web.md
=> companion-web: add note about the mavproxy endpoint required for the Rest API

resources/downloads.md
Seems like the link should point to Ardupilot now to avoid confusion.
=> Move ArduSub issues link to main ArduPilot repo

developers/pymavlink/companion_computer.py, developers/pymavlink/send_rangefinder_vision.py
=> pymavlink: Fix ping message to use unix time in microseconds

troubleshooting/troubleshooting.md
Reduced the bandwidth for troubleshooting from 40Mbps to 15Mbps.
=> Updated minimum bandwidth for troubleshooting

developers/dvl-integration.md
The steps are breaking constantly. this will help while we don't finish the dvl support properly.
=> dvl-integration: Add link to pre-built companion with dvl support

developers/pymavlink.md, developers/pymavlink/advanced_servo_gripper.py, developers/pymavlink/arm_disarm.py, developers/pymavlink/filter_messages.py, developers/pymavlink/message_qgc.py, developers/pymavlink/read_params.py, developers/pymavlink/read_write_params.py, developers/pymavlink/set_servo.py, developers/pymavlink/set_target_depth_attitude.py, developers/pymavlink/udp_connection.py
=> Pymavlink updates

.github/workflows/htmlproofer.yaml, developers/dvl-integration.md, introduction/hardware-options/additional-peripheral-devices/underwater-positioning.md, introduction/hardware-options/required-hardware/tether.md
- update to latest (tested working) build, on 0.0.28 with updated mavlink2rest
- download link now explicit to specific version (requires updating docs every time an updated build is made, but means it's more clear which build is in use)
=> developers: dvl: update build download link

reference/ardusub/joystick-setup-page.md
Updates depth hold flight mode description, removes reference to pitch/roll control bug that was fixed in 2019.
Fixes #201
=> reference: joystick: fix outdated depth hold description

developers/software-components.md, introduction/required-software.md, introduction/software-components-miro-board.md
Software components diagram (Miro board) linked to from two pages. Best to have a single source so the description is shared, and any updates to the page can be performed more efficiently.
=> Software components single source

developers/pymavlink/set_target_depth_attitude.py
Brought up [here](https://discuss.bluerobotics.com/t/regarding-pwm-signal-delays-setting-target-depth-type-masks-and-ned-system-setting-target-attitude-heartbeat-message/10492/4)
=> pymavlink: set_target_depth_attitude: fix typos

developers/pymavlink/set_target_depth_attitude.py
Adds clarity, and restores functionality on companion if someone wants to use it there.
=> developers: pymavlink: use type_mask flags

developers/pymavlink/set_target_depth_attitude.py
Non-essential because it's commented out anyway, but good to be as clear as possible.
=> developers: pymavlink: fix flag name typo

developers/dvl-integration.md
Updates installation instructions to at least specify that DVL functionality is available in 0.0.31.
I've kept the part about "DVL functionality requires a beta version of Companion", and the "beta" in the "Installing" heading - not sure if that's the best way of handling this or if it's better to go full out and just remove mention of beta.
=> developers: dvl-integration: update installation instructions

developers/pymavlink/request_message_interval.py
Response target is parameter 7, not parameter 4 (see https://mavlink.io/en/messages/common.html#MAV_CMD_SET_MESSAGE_INTERVAL)
Raised in [this forum post](https://discuss.bluerobotics.com/t/questions-about-mavlink-commands-and-the-pymavlink-documentation/11446).
=> developers: pymavlink: fix interval message

archive-notice.html, quick-start/vehicle-frame.md
- Fix text colour in archive warning (to handle light/dark transition)
- Add link to BlueROV2 output channel mapping (requested by Tony)
=> Minor archiving improvements

developers/opencv.md
Fix wrong delete logic and add compile information
=> developers: opencv: Update c++ example
